"use client";

import {
  BarChart3,
  FileArchive,
  FileImage,
  FileJson,
  FileSpreadsheet,
  FileText,
  Presentation,
  ReceiptText,
} from "lucide-react";
import * as XLSX from "xlsx";
import { Button } from "@/components/common/button";
import { Card, CardContent } from "@/components/common/card";
import { PageHeader } from "@/components/common/page-header";
import { useAuth } from "@/components/auth/auth-provider";
import { useProject } from "@/hooks/use-project";
import { useAppStore } from "@/state/app-store";
import { calculateDashboardMetrics, todayDateString } from "@/utils/dashboard";
import { formatCurrency, monthLabel } from "@/utils/dates";
import { can } from "@/utils/permissions";

function downloadBlob(name: string, blob: Blob) {
  const url = URL.createObjectURL(blob);
  const anchor = document.createElement("a");
  anchor.href = url;
  anchor.download = name;
  anchor.click();
  URL.revokeObjectURL(url);
}

export function ReportsPage({ projectId }: { projectId: string }) {
  const { user } = useAuth();
  const { project, workspace, role } = useProject(projectId);
  const addAudit = useAppStore((state) => state.addAudit);
  const showInternal = can(role, "VIEW_INTERNAL_RATES");
  const generatedAt = new Date().toISOString();
  const metadata = {
    project: project?.name ?? projectId,
    projectCode: project?.code,
    projectStartDate: workspace.settings.projectStartDate,
    generatedAt,
    generatedBy: user?.email,
    progressSource: workspace.settings.progressSource,
    baseline:
      workspace.poapBaselines.find((baseline) => baseline.active)?.name ??
      "No comparison baseline",
  };

  function audit(report: string) {
    if (!user) return;
    addAudit(projectId, {
      id: crypto.randomUUID(),
      userId: user.uid,
      email: user.email,
      projectId,
      timestamp: new Date().toISOString(),
      action: "REPORT_GENERATED",
      entity: report,
      summary: `${report} generated`,
      correlationId: crypto.randomUUID(),
    });
  }

  async function dashboardPdf(customerSafe: boolean) {
    const { jsPDF } = await import("jspdf");
    const metrics = calculateDashboardMetrics({
      settings: workspace.settings,
      forecastLines: workspace.forecastLines,
      actualEntries: workspace.actualEntries,
      activities: workspace.activities,
      today: todayDateString(),
    });
    const doc = new jsPDF({ unit: "mm", format: "a4" });
    doc.setFillColor(11, 31, 58);
    doc.rect(0, 0, 210, 38, "F");
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(20);
    doc.text(customerSafe ? "Customer Project Summary" : "Executive Dashboard", 15, 18);
    doc.setFontSize(10);
    doc.text(`${metadata.project} · ${metadata.projectCode ?? ""}`, 15, 28);
    doc.setTextColor(23, 32, 51);
    doc.setFontSize(11);
    doc.text(`Generated: ${new Date(generatedAt).toLocaleString("en-AU")}`, 15, 50);
    doc.text(`Progress source: ${metadata.progressSource.replaceAll("_", " ")}`, 15, 58);
    doc.text(`POAP baseline: ${metadata.baseline}`, 15, 66);
    doc.setFontSize(14);
    doc.text("Project health", 15, 82);
    const safeRows = [
      ["POAP completion", `${metrics.effectivePercentComplete.toFixed(1)}%`],
      ["Current project week", `W${metrics.currentWeek}`],
      ["Activities", String(workspace.activities.length)],
      [
        "Late activities",
        String(
          workspace.activities.filter(
            (activity) =>
              activity.endDate < todayDateString() &&
              activity.status !== "COMPLETE",
          ).length,
        ),
      ],
    ];
    const internalRows = [
      ["BAC", formatCurrency(metrics.bac)],
      ["AC", formatCurrency(metrics.ac)],
      ["EV", formatCurrency(metrics.ev)],
      ["EAC", formatCurrency(metrics.eac)],
      ["VAC", formatCurrency(metrics.vac)],
      ["Actual vs forecast days", metrics.actualVsForecastVariance.toFixed(2)],
    ];
    const rows = customerSafe ? safeRows : [...safeRows, ...internalRows];
    rows.forEach(([label, value], index) => {
      const y = 94 + index * 13;
      doc.setFillColor(index % 2 ? 247 : 240, index % 2 ? 249 : 244, 251);
      doc.roundedRect(15, y - 7, 180, 10, 2, 2, "F");
      doc.setFontSize(10);
      doc.text(label, 20, y);
      doc.setFont("helvetica", "bold");
      doc.text(value, 188, y, { align: "right" });
      doc.setFont("helvetica", "normal");
    });
    doc.setFontSize(8);
    doc.setTextColor(100, 112, 130);
    doc.text(`Generated by ${metadata.generatedBy}`, 15, 285);
    doc.save(
      `${metadata.projectCode ?? "Project"}_${customerSafe ? "Customer" : "Executive"}_Dashboard.pdf`,
    );
    audit(customerSafe ? "Customer Dashboard PDF" : "Executive Dashboard PDF");
  }

  async function poapPdf() {
    const { jsPDF } = await import("jspdf");
    const doc = new jsPDF({ orientation: "landscape", unit: "mm", format: "a4" });
    doc.setFillColor(11, 31, 58);
    doc.rect(0, 0, 297, 28, "F");
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(18);
    doc.text("POAP Delivery Plan", 12, 13);
    doc.setFontSize(9);
    doc.text(`${metadata.project} · Baseline: ${metadata.baseline}`, 12, 21);
    doc.setTextColor(23, 32, 51);
    const maxActivities = 25;
    workspace.activities.slice(0, maxActivities).forEach((activity, index) => {
      const y = 38 + index * 6.5;
      const startOffset =
        (new Date(`${activity.startDate}T12:00:00`).getTime() -
          new Date(`${workspace.settings.projectStartDate}T12:00:00`).getTime()) /
        86400000;
      const duration = Math.max(
        1,
        (new Date(`${activity.endDate}T12:00:00`).getTime() -
          new Date(`${activity.startDate}T12:00:00`).getTime()) /
          86400000 +
          1,
      );
      doc.setFontSize(7);
      doc.text(activity.name.slice(0, 38), 10, y + 3.5);
      const x = 80 + startOffset * 0.8;
      doc.setFillColor(activity.priority === "CRITICAL" ? 196 : 40, activity.priority === "CRITICAL" ? 61 : 116, activity.priority === "CRITICAL" ? 79 : 208);
      doc.roundedRect(x, y, Math.max(2, duration * 0.8), 4.2, 1, 1, "F");
    });
    doc.setFontSize(7);
    doc.setTextColor(100, 112, 130);
    doc.text(
      `Start ${metadata.projectStartDate} · ${workspace.settings.numberOfWeeks} weeks · Generated ${new Date(generatedAt).toLocaleString("en-AU")} by ${metadata.generatedBy}`,
      12,
      202,
    );
    doc.save(`${metadata.projectCode ?? "Project"}_POAP.pdf`);
    audit("POAP PDF");
  }

  function poapPng() {
    const width = 1600;
    const rowHeight = 38;
    const height = 100 + workspace.activities.length * rowHeight;
    const start = new Date(`${workspace.settings.projectStartDate}T12:00:00`);
    const scale = 1350 / (workspace.settings.numberOfWeeks * 7);
    const escape = (value: string) =>
      value.replace(/[&<>"']/g, (char) => `&#${char.charCodeAt(0)};`);
    const rows = workspace.activities
      .map((activity, index) => {
        const startOffset =
          (new Date(`${activity.startDate}T12:00:00`).getTime() -
            start.getTime()) /
          86400000;
        const duration =
          (new Date(`${activity.endDate}T12:00:00`).getTime() -
            new Date(`${activity.startDate}T12:00:00`).getTime()) /
            86400000 +
          1;
        const y = 72 + index * rowHeight;
        return `<text x="20" y="${y + 17}" font-family="Arial" font-size="12" fill="#172033">${escape(activity.name.slice(0, 28))}</text><rect x="${230 + startOffset * scale}" y="${y + 4}" width="${Math.max(3, duration * scale)}" height="22" rx="5" fill="${activity.colour}"/>`;
      })
      .join("");
    const svg = `<svg xmlns="http://www.w3.org/2000/svg" width="${width}" height="${height}"><rect width="100%" height="100%" fill="#f7f9fb"/><rect width="100%" height="54" fill="#0b1f3a"/><text x="20" y="24" fill="white" font-family="Arial" font-size="20" font-weight="700">POAP Delivery Plan</text><text x="20" y="43" fill="#b9c8da" font-family="Arial" font-size="11">${escape(metadata.project)}</text>${rows}</svg>`;
    const image = new Image();
    const svgUrl = URL.createObjectURL(
      new Blob([svg], { type: "image/svg+xml" }),
    );
    image.onload = () => {
      const canvas = document.createElement("canvas");
      canvas.width = width;
      canvas.height = height;
      canvas.getContext("2d")?.drawImage(image, 0, 0);
      canvas.toBlob((blob) => {
        if (blob)
          downloadBlob(`${metadata.projectCode ?? "Project"}_POAP.png`, blob);
      });
      URL.revokeObjectURL(svgUrl);
    };
    image.src = svgUrl;
    audit("POAP PNG");
  }

  async function poapPowerPoint() {
    const PptxGenJS = (await import("pptxgenjs")).default;
    const pptx = new PptxGenJS();
    pptx.layout = "LAYOUT_WIDE";
    pptx.author = user?.displayName ?? "PTracker";
    pptx.subject = `${metadata.project} POAP`;
    pptx.title = "POAP Delivery Plan";
    const slide = pptx.addSlide();
    slide.background = { color: "F5F7FA" };
    slide.addShape(pptx.ShapeType.rect, {
      x: 0,
      y: 0,
      w: 13.333,
      h: 0.7,
      fill: { color: "0B1F3A" },
      line: { color: "0B1F3A" },
    });
    slide.addText("POAP Delivery Plan", {
      x: 0.35,
      y: 0.16,
      w: 4,
      h: 0.3,
      fontSize: 20,
      bold: true,
      color: "FFFFFF",
    });
    const scale = 10.2 / (workspace.settings.numberOfWeeks * 7);
    const start = new Date(`${workspace.settings.projectStartDate}T12:00:00`);
    workspace.activities.slice(0, 22).forEach((activity, index) => {
      const y = 0.95 + index * 0.27;
      const startOffset =
        (new Date(`${activity.startDate}T12:00:00`).getTime() - start.getTime()) /
        86400000;
      const duration =
        (new Date(`${activity.endDate}T12:00:00`).getTime() -
          new Date(`${activity.startDate}T12:00:00`).getTime()) /
          86400000 +
        1;
      slide.addText(activity.name, {
        x: 0.25,
        y,
        w: 2.35,
        h: 0.2,
        fontSize: 7,
        color: "172033",
        breakLine: false,
      });
      slide.addShape(pptx.ShapeType.roundRect, {
        x: 2.75 + startOffset * scale,
        y,
        w: Math.max(0.04, duration * scale),
        h: 0.18,
        rectRadius: 0.03,
        fill: { color: activity.colour.replace("#", "") },
        line: { color: activity.colour.replace("#", "") },
      });
    });
    slide.addText(
      `Baseline: ${metadata.baseline} · Generated ${new Date(generatedAt).toLocaleString("en-AU")} · ${metadata.generatedBy}`,
      { x: 0.25, y: 7.15, w: 12.6, h: 0.2, fontSize: 7, color: "68778C" },
    );
    await pptx.writeFile({
      fileName: `${metadata.projectCode ?? "Project"}_POAP.pptx`,
    });
    audit("POAP PowerPoint");
  }

  function actualsCsv() {
    const rows = workspace.actualResources.map((resource) => {
      const row: Record<string, string | number> = {
        Stream: resource.stream,
        Role: resource.role,
        Code: resource.code,
        Name: resource.name,
        Location: resource.location,
        ...(showInternal ? { "Day Rate": resource.dayRate } : {}),
      };
      for (let week = 1; week <= workspace.settings.numberOfWeeks; week += 1) {
        row[`W${week}`] =
          workspace.actualEntries.find(
            (entry) =>
              entry.resourceId === resource.id && entry.week === week,
          )?.days ?? 0;
      }
      return row;
    });
    downloadBlob(
      `${metadata.projectCode ?? "Project"}_Actuals.csv`,
      new Blob([XLSX.utils.sheet_to_csv(XLSX.utils.json_to_sheet(rows))], {
        type: "text/csv",
      }),
    );
    audit("Actuals CSV");
  }

  function monthlyExcel() {
    const monthMap = new Map<string, { forecast: number; actual: number }>();
    for (let week = 1; week <= workspace.settings.numberOfWeeks; week += 1) {
      const month = monthLabel(workspace.settings.projectStartDate, week);
      const current = monthMap.get(month) ?? { forecast: 0, actual: 0 };
      current.forecast += workspace.forecastLines.reduce(
        (total, line) => total + (line.weeks[`W${week}`] ?? 0),
        0,
      );
      current.actual += workspace.actualEntries
        .filter((entry) => entry.week === week)
        .reduce((total, entry) => total + entry.days, 0);
      monthMap.set(month, current);
    }
    const rows = [...monthMap].map(([month, value]) => ({
      Month: month,
      Forecast: value.forecast,
      Actual: value.actual,
      Variance: value.actual - value.forecast,
    }));
    const book = XLSX.utils.book_new();
    XLSX.utils.book_append_sheet(
      book,
      XLSX.utils.json_to_sheet(rows),
      "Monthly Reconciliation",
    );
    XLSX.writeFile(
      book,
      `${metadata.projectCode ?? "Project"}_Monthly_Reconciliation.xlsx`,
    );
    audit("Monthly Reconciliation Excel");
  }

  async function invoicePdf(invoiceId: string) {
    const invoice = workspace.invoices.find((item) => item.id === invoiceId);
    if (!invoice) return;
    const { jsPDF } = await import("jspdf");
    const doc = new jsPDF();
    doc.setFillColor(11, 31, 58);
    doc.rect(0, 0, 210, 35, "F");
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(20);
    doc.text("Invoice Evidence Summary", 15, 17);
    doc.setFontSize(10);
    doc.text(invoice.invoiceNumber, 15, 27);
    doc.setTextColor(23, 32, 51);
    const rows = [
      ["Project", metadata.project],
      ["Code", invoice.code],
      ["Period", invoice.periodName],
      ["Actual Days", invoice.actualDays.toFixed(2)],
      ["Forecast Days", invoice.forecastDays.toFixed(2)],
      ["Invoice Amount", formatCurrency(invoice.amount)],
      ["Status", invoice.status.replaceAll("_", " ")],
      ["Evidence captured", new Date(invoice.evidencePack.capturedAt).toLocaleString("en-AU")],
    ];
    rows.forEach(([label, value], index) => {
      doc.setFontSize(10);
      doc.text(label, 15, 53 + index * 12);
      doc.setFont("helvetica", "bold");
      doc.text(value, 195, 53 + index * 12, { align: "right" });
      doc.setFont("helvetica", "normal");
    });
    doc.save(`${invoice.invoiceNumber}.pdf`);
    audit("Invoice PDF");
  }

  function evidencePack(invoiceId: string) {
    const invoice = workspace.invoices.find((item) => item.id === invoiceId);
    if (!invoice) return;
    downloadBlob(
      `${invoice.invoiceNumber}_Evidence_Pack.json`,
      new Blob(
        [
          JSON.stringify(
            {
              metadata,
              invoice,
              fiReconciliation: workspace.fiUploads.at(-1)?.summary,
            },
            null,
            2,
          ),
        ],
        { type: "application/json" },
      ),
    );
    audit("Invoice Evidence Pack");
  }

  function auditExport() {
    downloadBlob(
      `${metadata.projectCode ?? "Project"}_Audit.json`,
      new Blob([JSON.stringify(workspace.auditLog, null, 2)], {
        type: "application/json",
      }),
    );
    audit("Audit Export");
  }

  const reports = [
    {
      icon: BarChart3,
      title: "Executive Dashboard PDF",
      copy: "Financial KPIs, schedule health, active baseline and generation metadata.",
      internal: true,
      action: () => void dashboardPdf(false),
    },
    {
      icon: FileText,
      title: "Customer-safe Dashboard PDF",
      copy: "Schedule progress and delivery health without internal rates or costs.",
      internal: false,
      action: () => void dashboardPdf(true),
    },
    {
      icon: FileText,
      title: "POAP Landscape PDF",
      copy: "Presentation-ready Gantt summary with baseline and generation metadata.",
      internal: false,
      action: () => void poapPdf(),
    },
    {
      icon: FileImage,
      title: "POAP PNG",
      copy: "High-resolution image for status packs and collaboration channels.",
      internal: false,
      action: poapPng,
    },
    {
      icon: Presentation,
      title: "POAP PowerPoint",
      copy: "Editable widescreen Gantt slide for executive presentation packs.",
      internal: false,
      action: () => void poapPowerPoint(),
    },
    {
      icon: FileSpreadsheet,
      title: "Actuals CSV",
      copy: "Resource and weekly actual data for downstream analysis.",
      internal: true,
      action: actualsCsv,
    },
    {
      icon: FileSpreadsheet,
      title: "Monthly Reconciliation Excel",
      copy: "Forecast, actual and variance by calendar month.",
      internal: true,
      action: monthlyExcel,
    },
    {
      icon: FileJson,
      title: "Audit Export",
      copy: "Append-only project audit history with user and correlation IDs.",
      internal: true,
      action: auditExport,
    },
  ];

  return (
    <>
      <PageHeader
        eyebrow={project?.code}
        title="Reports and exports"
        description="Generate authenticated, project-scoped documents. Customer-safe reports deliberately exclude rate and cost collections."
      />
      <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">
        {reports
          .filter((report) => showInternal || !report.internal)
          .map(({ icon: Icon, title, copy, action }) => (
            <Card key={title}>
              <CardContent className="flex h-full flex-col">
                <span className="w-max rounded-xl bg-[#e7f0f8] p-3 text-[#285986]">
                  <Icon className="h-6 w-6" />
                </span>
                <h2 className="mt-4 text-base font-bold">{title}</h2>
                <p className="mt-2 flex-1 text-sm leading-6 text-[#68778c]">
                  {copy}
                </p>
                <Button variant="outline" className="mt-5" onClick={action}>
                  Generate report
                </Button>
              </CardContent>
            </Card>
          ))}
      </div>

      {showInternal ? (
        <Card className="mt-5">
          <CardContent>
            <div className="flex items-center gap-3">
              <span className="rounded-xl bg-[#eaf0f6] p-3 text-[#2c5f8f]">
                <ReceiptText className="h-6 w-6" />
              </span>
              <div>
                <h2 className="text-base font-bold">Invoice documents</h2>
                <p className="mt-1 text-sm text-[#68778c]">
                  Export the frozen invoice summary or its complete JSON evidence
                  pack.
                </p>
              </div>
            </div>
            {workspace.invoices.length ? (
              <div className="mt-5 space-y-2">
                {workspace.invoices.map((invoice) => (
                  <div
                    key={invoice.id}
                    className="flex flex-wrap items-center gap-3 rounded-xl border border-[#e1e7ee] p-3"
                  >
                    <div className="min-w-0 flex-1">
                      <p className="font-bold">{invoice.invoiceNumber}</p>
                      <p className="mt-1 text-xs text-[#758397]">
                        {invoice.periodName} · {formatCurrency(invoice.amount)}
                      </p>
                    </div>
                    <Button
                      variant="outline"
                      size="sm"
                      onClick={() => void invoicePdf(invoice.id)}
                    >
                      <FileText className="h-4 w-4" />
                      PDF
                    </Button>
                    <Button
                      variant="outline"
                      size="sm"
                      onClick={() => evidencePack(invoice.id)}
                    >
                      <FileArchive className="h-4 w-4" />
                      Evidence pack
                    </Button>
                  </div>
                ))}
              </div>
            ) : (
              <p className="mt-5 text-sm text-[#758397]">
                No invoices are available yet.
              </p>
            )}
          </CardContent>
        </Card>
      ) : null}
    </>
  );
}
